# Generated by Django 6.0 on 2025-12-29 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gas_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasbooking',
            name='cylinder_type',
            field=models.CharField(choices=[('Small', 'Small Domestic (6kg) - Rs. 2,000'), ('Standard', 'Standard Home (11.8kg) - Rs. 3,500'), ('Commercial', 'Commercial (45.4kg) - Rs. 13,000')], default='Standard', max_length=50),
        ),
        migrations.AddField(
            model_name='gasbooking',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
