# Generated by Django 6.0 on 2025-12-29 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gas_app', '0003_contactmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gasbooking',
            name='city',
        ),
        migrations.AlterField(
            model_name='gasbooking',
            name='cylinder_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='gasbooking',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
    ]
